# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{colorer}
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Domizio Demichelis"]
  s.date = %q{2010-09-17}
  s.description = %q{Colorer adds the basic ANSI styles to any string, allowing also to define your own stiles}
  s.email = %q{dd.nexus@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "colorer.gemspec",
     "lib/colorer.rb",
     "test/basic.irt",
     "test/custom.irt",
     "test/sgr.irt"
  ]
  s.homepage = %q{http://github.com/ddnexus/colorer}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Easy ANSI code coloring for strings}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<irt>, [">= 0.7.1"])
    else
      s.add_dependency(%q<irt>, [">= 0.7.1"])
    end
  else
    s.add_dependency(%q<irt>, [">= 0.7.1"])
  end
end

